server:
  port: 9105

liquibase:
  change-log: classpath:db/changelog/changelog.xml
  default-schema: schema_order
  drop-first: false
  enabled: true

spring:
  cloud:
    stream:
      bindings:
        cancel_reservation_output:
          binder: rabbit
          destination: cancelReservation
          group: default
          content-type: application/json
          producer:
            required-groups: default
        waiting_for_payment_output:
          binder: rabbit
          destination: waitingForPayment
          group: default
          content-type: application/json
          producer:
            required-groups: default
        arrange_shipment_output:
          binder: rabbit
          destination: arrangeShipment
          group: default
          content-type: application/json
          producer:
            required-groups: default
        payment_succeeded_input:
          binder: rabbit
          destination: paymentSucceeded
          group: default
          content-type: application/json
          consumer:
            max-attempts: 3
    loadbalancer:
      retry:
        enabled: true

product-service:
  ribbon:
    ConnectTimeout: 250
    ReadTimeout: 1000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2

---
spring:
  profiles: development

---
spring:
  profiles: test