info:
  version: @project.version@

spring:
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    jackson:
      time-zone: GMT+8
    serialization:
      write_dates_as_timestamps: false
  cloud:
    stream:
      defaultBinder: rabbit
      kafka:
        binder:
          zkNodes: ${KAFKA_HOST:localhost}
          defaultZkPort: 2181
          brokers: ${KAFKA_HOST:localhost}
          defaultBrokerPort: 9092
          autoCreateTopics: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    publisher-returns: true
    listener:
      default-requeue-rejected: true
      prefetch: 1
      transaction-size: 1
      retry:
        enabled: true
        max-attempts: 3
    template:
      retry:
        enabled: true
        max-attempts: 3
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379
    database: 0
    pool:
      max-active: 10
      max-idle: 10
      max-wait: -1
      min-idle: 0
  cache:
    type: redis
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  sleuth:
    sampler:
      percentage: 1
  boot:
    admin:
      url: http://${ADMIN_HOST:localhost}:8080
      client:
        enabled: false
        prefer-ip: true

management:
  security:
    enabled: false

security:
  user:
    name: gavin
    password: gavin
  basic:
    enabled: false
  ignored: /swagger**,/swagger**/**,/webjars/**,/v2/**

logging:
  level:
    org.springframework.security: DEBUG

ribbon:
  ConnectTimeout: 600000
  ReadTimeout: 600000
  eureka:
    enabled: true

feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000
            interruptOnTimeout: true
      circuitBreaker:
        enabled: true
        errorThresholdPercentage: 60
      fallback:
        enabled: true